### PR TITLE
Require Node v8

### PR DESCRIPTION
**Pull request by abyss**
Changed node install to v8, and also fixed inconsistent tabs/spaces.

### CODE REVIEW

**Comment by foxfirecodes** [comment]
Actually, I’d prefer if this installed v9. If you make that change, I’ll merge.

**Comment by abyss** [comment]
You don't currently require anything v9 uses as far as I can tell - and v8 is LTS where v9 isn't. Would suggest sticking with LTS unless you implement v9 features.

**Comment by foxfirecodes** [comment]
Maybe it's just me, but I tend to encourage people to stay as far ahead of the game as possible. But from a less idealistic and more practical standpoint, by having them install v9 *now*, it will be longer until those people will need to update to a newer Node version. I feel like this is something we should discuss in #contributors, get some other opinions.

**Comment by foxfirecodes** [comment]
Ah, you know what, I'm just gonna go with v8. I can always change it later if I must, and I'm working on making it possible to install SharpBot more easily anyways.

**Pull request merged**
